name: "Close stale issues and PRs"
on:
  schedule:
    - cron: "30 1 * * *" # run at 0130 UTC

jobs:
  stale:
    uses: AstroNvim/.github/.github/workflows/stale.yml@97cdc3810853afdcccf8e40f7262bd5ec397c8fa # v1
    permissions:
      issues: write
      pull-requests: write
